### ISSUE TITLE
Top 50 users dataset

### ISSUE THREAD

**Issue by hsson** [kandidat-highlights/data#1]
Please fix a dataset that contains top 50 users.

**Comment by Mxiim** [comment]
@hsson Should this be title, users? With all users interested in same title on same row/datapoint?

**Comment by hsson** [comment]
Yes, this should be like the top_5 data set (not top_5_single). So a row can have multiple users. Also, for compatibility with concatenated input consider adding subreddits as well. I guess it depends on whether the [pull request](https://github.com/kandidat-highlights/model/pull/12) gets accepted or not.
